translators:
  zh-x-test:
    model_or_config_dir: D:\kidden\github\yimt\service\infer.yaml
    sp_src_path: D:\dataset\mnmt\sp\en-zh.tsv.zh-sp-32000.model
    batch_size: 128
    pretok_src: false
    pretok_tgt: false
    directions:
      - zh-ja
      - zh-ar

  enzh:
    model_or_config_dir: D:\dataset\en-zh\040607\train\infer.yaml
    sp_src_path: D:\dataset\en-zh\040607\train\en-zh-all-new-0.66.sf.tsv.en-20000000-sp-36000.model
    batch_size: 128
    pretok_src: false
    pretok_tgt: false
    directions:
      - en-zh

  zhen:
    model_or_config_dir: D:\dataset\en-zh\040618\zhen\infer.yaml
    sp_src_path: D:\dataset\en-zh\040607\train\en-zh-all-new-0.66.sf.tsv.zh-10000000-sp-36000.model
    batch_size: 128
    pretok_src: false
    pretok_tgt: false
    directions:
      - zh-en

languages:
  - {code: en, name: English, cname: 英语}
  - {code: zh, name: Chinese, cname: 汉语}
  - {code: ja, name: Japanese, cname: 日语}
  - {code: ar, name: Arabic, cname: 阿拉伯语}
