model: D:\dataset\pt-mnmt\lm\run\model_step_46000.pt

# share_vocab: true

transforms: [sentencepiece]
src_subword_model: D:\dataset\pt-mnmt\lm\train.csv-sp-32000.model
tgt_subword_model: D:\dataset\pt-mnmt\lm\train.csv-sp-32000.model

gpu: 0

batch_type: sents
batch_size: 16

src: None
