
share_vocab: true
src_vocab: /root/autodl-tmp/lm/wiki103.vocab

transforms: [filtertoolong]
src_seq_length: 512
tgt_seq_length: 512

# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    corpus_1:
        path_src: /root/autodl-tmp/lm/train.csv.tok
    valid:
        path_src: /root/autodl-tmp/lm/test.csv.tok

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: /root/autodl-tmp/lm/run/model
save_checkpoint_steps: 1000
keep_checkpoint: 6
train_steps: 80000
valid_steps: 1000
report_every: 100
tensorboard: true
tensorboard_log_dir: /root/autodl-tmp/lm/run/tensorboard

early_stopping: 3
early_stopping_criteria: ppl

# Model
model_task: lm
encoder_type: transformer_lm
decoder_type: transformer_lm
position_encoding: true
dec_layers: 6
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]

bucket_size: 262144
batch_size: 4096
valid_batch_size: 2048
batch_type: tokens

model_type: fp16
optim: adam
accum_count: 4
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"
